### ISSUE TITLE
LAYTYP for MODFLOW 6

### ISSUE THREAD

**Issue by jdhughes-dev** [MODFLOW-USGS/modpath-v7#1]
`ICELLTYPE` for MODFLOW 6 is dimensioned to `(nlay, nrow, ncol)` instead of `nlay`. MODPATH 7 basic file (`MPBAS`) should accommodate this difference.

**Comment by aprovost-usgs** [comment]
Comment in pr_ReadData of ModpathBasicDataModule:

  ! Read LAYTYP only for MODFLOW-2005 and MODFLOW-USG datasets.
  ! Loop through layers and set the cell type for all cells in a 
  ! layer equal to the LAYTYP value for the layer.
  ! LAYTYP is not read for MODFLOW-6 datasets. Instead, cell types 
  ! for all cells are read directly for from the binary grid file.
 
For MF6-based runs, LAYTYP is not read, and ICELLTYPE is read from the binary grid file (not MPBAS). 
(In resolving a related issue brought up by WZ and RW, the working copy of the input instructions has been updated to reflect the fact that LAYTYP is not read for MF6-based runs.)
