### ISSUE TITLE
pathline output format width.precision

### ISSUE THREAD

**Issue by jdhughes-dev** [MODFLOW-USGS/modpath-v7#13]
Lines 156-157 in `ParticleManager.f90`:

```
        write(outUnit, "(i10,7e16.8,3I10)")  &
             c%CellNumber, modelX, modelY, c%GlobalZ, c%TrackingTime,  &
             c%LocalX, c%LocalY, c%LocalZ, c%Layer, stressPeriod, timeStep
```

`e16.8` format does not work for numbers with more than 3 digits in the exponent (for example, `0.22478670E-309` which results in `0.22478670-309` in the pathline output.

A possible fix is convert `e16.8` to `e16.7` or maybe a better fix would be [`es23.16`](http://www.fortran90.org/src/best-practices.html), which would not result in any loss of precision. A larger width may affect post-processing programs.

**Comment by aprovost-usgs** [comment]
This is likely an issue only for numbers that happen to come out extremely small but not quite zero.  (If you have huge numbers on the order of E+100 or more in your output, your problem is scaled really oddly or you're using strange units!)  In that case, loss of precision is probably not a concern, so I think a trap for such tiny numbers that switches to E16.7 should be fine.

**Comment by christianlangevin** [comment]
Switching to the following csv format would probably be something to consider in the future.  I think this format gets around many of the issues that we have with output precision, and should ultimately reduce output file size by eliminating useless whitespace.

```
          WRITE(99,'(*(G0,:,","))') N, this%RHS(N), (this%ja(i),i=i1,i2), &
                        (this%AMAT(I),I=I1,I2)

```

**Comment by aprovost-usgs** [comment]
Fixed the issue by forcing a 3-digit exponent in the columnwise output to the endpoint, pathline, and timeseries files.  Did this by adding "e3" to the output formats.  Also changed "e" to "es" to shift digits leftward, eliminating the leading zero and thereby preserving the original output precision.
