### ISSUE TITLE
Bug when using cell template for particles defined by node

### ISSUE THREAD

**Issue by jdhughes-dev** [MODFLOW-USGS/modpath-v7#14]
Bug detected when using particle starting location data – Input Style 3 and TemplateSubdivisionType = 2.

Error on line 687 in StartingLocationReader.f90 - n is uninitialized. This line can be deleted or commented out.

`pGroup%Particles(n)%InitialFace = 0`

to 

`! pGroup%Particles(n)%InitialFace = 0`

or 

`just delete the line`

**Comment by aprovost-usgs** [comment]
Commented out the line as recommended. Also eliminated the declaration of n, since is was not being used for anything else in that subroutine.
