### ISSUE TITLE
Unnecessary restriction on MF6 DIS grid spacing

### ISSUE THREAD

**Issue by aprovost-usgs** [MODFLOW-USGS/modpath-v7#22]
MODPATH checks grid-spacing ratios to make sure they are consistent with "smoothed" quadtree or quadpatch grid refinement.  But it appears to be applying the check even to MF6 DIS grids, when it is not necessary, resulting in an "Invalid grid spacing structure" error when the grid spacing in a given direction between two adjacent cells differs by a factor other than 2 (or 0.5).  This restriction should be relaxed.  The restriction does not apply, and the error does not occur, for MF2005 DIS grids.  (Issue identified by DS.)

**Comment by jtwhite79** [comment]
We just ran into this issue too with a structured irregular grid (converted from mf2005 to mf6).  Is there an easy work around? Or time line to address this issue?  Thanks!

**Comment by ghost** [comment]
Same issue here!

**Comment by christianlangevin** [comment]
@jtwhite79 by any chance do you have a small example that you could post to this issue that shows the problem, just to make sure that we get it fixed properly?  We'll try to get on this soon.  Thanks for checking in on this.

**Comment by ghost** [comment]
Here is a super simple 1-layer MF6 model with some grid refinement. Throws an error when running MP7 (on Mac): Invalid grid spacing structure. stop.
[test.zip](https://github.com/MODFLOW-USGS/modpath-v7/files/5889570/test.zip)

**Comment by aprovost-usgs** [comment]
@khm293 Thanks very much, Katie

**Comment by aprovost-usgs** [comment]
@jtwhite79 @khm293 For all types of grids except an MF-2005 DIS grid, MODPATH 7 does a check to make sure the grid is consistent with a smoothed quad-refined grid. This is done in a routine that computes cell face assignments and is shared by all types of grids except MF-2005 DIS grids (even though, strictly speaking, a MF6 DIS grid doesn't need such a check, either).  Unfortunately, the check is too restrictive in that it doesn't allow a regular grid with delx and/or dely varying by factors other than 0.5, 1.0, or 2.0 from one row or column to the next. The checking has now been updated to allow that. It successfully handles the example supplied by khm293, which has a regular grid with delx and dely varying by factors other than 0.5, 1.0, or 2.0, and MODPATH 7 example 2a, which has a grid with three levels of smooth quad refinement. The updated source code has been posted (commit f382506f094805d0e3bbc917ffb0c7cbe5cb91bd), and we're working on a USGS release that includes this update.

**Comment by jtwhite79** [comment]
Thanks @aprovost-usgs for the quick response!  We are testing now.

**Comment by aprovost-usgs** [comment]
Thanks @jtwhite79, let us know how the testing goes

**Comment by ianp94** [comment]
This seems to still be an issue. Any updates?

**Comment by aprovost-usgs** [comment]
@ianp94, an official release that includes this fix (commit f382506) is targeted for June or early July.

**Comment by Neilt100** [comment]
@aprovost-usgs Hi,  I'm encountering this issue using a MF6 DISV model built using Gridgen.  The maximum grid refinement is a factor of 4.  I've downloaded development version of modpath7 and recompiled, but this error still pops up?  So far as I can see the development files I downloaded included the fix from the commit listed above.  Just wondering if there is an update?

Many thanks,

**Comment by aprovost-usgs** [comment]
@Neilt100 Hi, I just want to verify that the issue you're encountering is the one that was meant to be addressed in the fix. The fix was to allow an MF6 DIS grid with uneven spacing that varies by factors other than 0.5 or 2 -- for example, the first column of cells is 10 m wide, the second is 40 m wide, the third is 160 m wide, etc (a factor of 4 moving to the right). It was not intended to relax the requirement that in a quad-refined DISV grid, two adjacent cells must differ by no more than one level of refinement. So a cell can share a given edge with either 1 or 2 adjacent cells, but not with 4 cells, i.e., you still can't match a cell edge with 4 smaller cell edges. That is an inherent requirement for Pollock's quad-refined tracking method.  However, if you meant that each cell is divided into no more than 4 smaller cells (a 2x2 refinement), so that each cell edge is matched with no more than 2 smaller cell edges, then that should be allowed, provided the 4 smaller cells are of equal dimensions (each 2x2 refinement divides the cell exactly in half in each direction).

**Comment by Neilt100** [comment]
@aprovost-usgs Hi.  So far as I can tell, each cell is divided into no more than 4 smaller cells, which I think is enforced by Gridgen?  So the spacing factors shouldn't vary by more than 0.5 or 2- and perhaps my issue wasn't meant to be addressed by the fix.  I've attached the modpath simulation files if that is helpful.
[modpath.zip](https://github.com/MODFLOW-USGS/modpath-v7/files/6964534/modpath.zip)

**Comment by christianlangevin** [comment]
Gridgen should meet the shared edge constraints, but only if the quadtree smoothing parameters are set correctly.

**Comment by Neilt100** [comment]
Smoothing in the gridgen Quadtree_Builder block was set to 'full', but no settings were specified for 'HORIZONTAL_SMOOTHING_LEVEL' or 'VERTICAL_SMOOTHING_LEVEL'- would this make a difference, or are these set to 1 by default?

**Comment by Neilt100** [comment]
@aprovost-usgs  Hi,  I think I have found the source of my error, which I think is related to the precision of the grid system I used and the tolerance for snapping to 0.5, 1 or 2 as the ratio between grid cells.  Essentially, the precision with which the coordinates were written to the disv file wasn't accurate enough.  Amending the grid system from NZTM to a local coordinate system (and rerunning gridgen to regenerate the disv file) seems to have fixed the error. Hopefully this helps others if they encounter the same issue.  Thanks.

**Comment by aprovost-usgs** [comment]
@Neilt100 I was out yesterday but had started to look into the issue based on the example you sent the day before, and it was indeed looking like a precision issue.  I'm glad you were able to get to the bottom of this, and thanks for posting your findings for the benefit of others who might also encounter it.
