### ISSUE TITLE
Tracking within inset MODFLOW 6 models

### ISSUE THREAD

**Issue by christianlangevin** [MODFLOW-USGS/modpath-v7#26]
User reports (https://github.com/modflowpy/flopy/issues/1251) that MODPATH version 7 will not track particles for a MODFLOW 6 inset model.  Not sure of the best way to handle this, but it would be nice if MODPATH would be able to track particles within the inset model.  I'm guessing that MODPATH doesn't recognize the exchanges fluxes that are written to inset models.  They are labeled with the FLOW_JA_FACE text string.

Perhaps there is no need to worry about this now if the dedicated particle tracker for MODFLOW 6 is getting close.

**Comment by aprovost-usgs** [comment]
MODPATH works with only a single model at a time.  However, it supports quad-refined grids, so if the inset arrangement can be reformulated as a single, quad-refined grid, that would be the way to go.

The first release of the MODFLOW 6 particle tracker is expected in early 2022.  That initial release will not be able to handle exchanges between flow models, either, but that capability will be added eventually.

**Comment by christianlangevin** [comment]
This comment was in reference to tracking on a single grid, but one that is embedded in a parent grid.  Ideally, particle tracking should work in an embedded grid, in which case particles will terminate at the grid boundary.

**Comment by aprovost-usgs** [comment]
I misunderstood - thanks for clarifying.  I'll look into why MODPATH apparently can't handle that.

**Comment by aprovost-usgs** [comment]
@RyanConway91 You reported that MP7 will not work on the cbb file if exchanges flows are written to the cbb.  Does MODPATH crash, or does it run but appear to ignore/misread those flows?

**Comment by RyanConway91** [comment]
I am using the provisional version (I have an MF6 model with irregular r,c,l dis). This is the error I get:

***@***.***
This is the last line of the lst
***@***.***


My current solution is to re-run the model with the exchange flows as wells. MP7 works on the cbb produced this way.

   Ryan J. Conway
   Hydrogeologist
   Minneapolis, MN office: 952.832.2846
   cell: 715.338.4386
   ***@***.***
   www.barr.com

***@***.***<www.barr.com>

If you no longer wish to receive marketing e-mails from Barr, respond to ***@***.*** and we will be happy to honor your request.

**Comment by aprovost-usgs** [comment]
@RyanConway91 Thanks for your reply.  It would be helpful if I could run your problem myself.  Please feel free to contact me directly at aprovost@usgs.gov and we can figure out how best to transfer your files.

**Comment by RyanConway91** [comment]
You should be able to access the files here:

https://drive.google.com/drive/folders/1fWOYcDMB2Y0XN74ZqvsQR3fKBHfgS2Zk?usp=sharing

Thanks


   Ryan J. Conway
   Hydrogeologist
   Minneapolis, MN office: 952.832.2846
   cell: 715.338.4386
   ***@***.***
   www.barr.com

***@***.***<www.barr.com>

If you no longer wish to receive marketing e-mails from Barr, respond to ***@***.*** and we will be happy to honor your request.

**Comment by aprovost-usgs** [comment]
@RyanConway91 Got the files -- thanks very much!

**Comment by aprovost-usgs** [comment]
@RyanConway91 When multiple FLOW-JA-FACE entries are written to the budget (as when there are exchanges), MODPATH was interpreting the last entry as the main listing for the model connections. This resulted in improper dimensioning of the associated array.  Commit https://github.com/MODFLOW-USGS/modpath-v7/commit/316e50fb935dd2ec6e5568a21332f85b2186f31c fixes this so that only the entry with imeth=0 or 1 is recognized as the main entry for model connections. An updated provisional executable has been posted in modpath-v7/msvs/bin_PROVISIONAL/ -- please see the accompanying README_provisional.txt file for relevant disclaimers.
