### ISSUE TITLE
pathline file formatting with large (3-digit) exponents

### ISSUE THREAD

**Issue by dbrakenhoff** [MODFLOW-USGS/modpath-v7#27]
I'm trying to use ModPath (version 7.2.001) to calculate pathlines for particles with an MF6 model. ModPath runs fine, but when reading the resulting Pathline file flopy errors with the following message:

```Python
ValueError: could not convert string to float: '0.38687557-107'
```

Once exponents reach triple digits (not sure why it gets this small...) the `E` is removed from the number formatting, causing flopy to crash while reading the file. Oddly, I've been able to read the resulting pathline file for different scenarios of the same model before without any issues, so these small numbers seem to be the result of some change(s) in my MF6 model. 

This seems related to the closed issue #13, which suggested this issue was fixed...?

Example snippet from my Pathline file with missing E 4th to last column in the last row:
```    
    786118  0.16200000E+06  0.43670000E+06 -0.73863412E+02  0.10520602E+07  0.00000000E+00  0.25115594E-99  0.82207959E-01        46         2         1
    786117  0.16160000E+06  0.43670000E+06 -0.75687806E+02  0.11183175E+07  0.00000000E+00  0.12106597E-99  0.11881285E+00        46         2         1
    786116  0.16120000E+06  0.43670000E+06 -0.75125220E+02  0.11831327E+07  0.00000000E+00  0.22230409-101  0.28246969E+00        46         2         1
```

Thanks in advance for any help!

**Comment by aprovost-usgs** [comment]
@dbrakenhoff This does appear to be the same issue as https://github.com/MODFLOW-USGS/modpath-v7/issues/13. The fix is included in the provisional executable posted in modpath-v7/msvs/bin_PROVISIONAL/ -- please see the accompanying README_provisional.txt file for relevant disclaimers.

**Comment by dbrakenhoff** [comment]
Ah thanks for pointing to the develop version. When I saw the closed issue I thought the issue had already been dealt with in the previous release!

**Comment by aprovost-usgs** [comment]
@dbrakenhoff No worries :)

**Comment by dbrakenhoff** [comment]
One more question: is there a precompiled linux version of the develop version of modpathv7 by any chance? Or do I have to compile from source myself?

Edit: I managed to use the mac makefile to compile it on my machine.

**Comment by aprovost-usgs** [comment]
@dbrakenhoff README_provisional.txt summarizes the approach to the provisional code:

The preliminary executable code is provided temporarily for evaluation purposes
as a courtesy to users who are unable to compile the source code. Only a 64-bit
Windows executable is provided. The name of the executable file references
the MODPATH 7 github repository commit number on which the executable is
based. The executable will not necessarily be updated after every commit.

Thanks for updating your comment -- I'm glad you were able to successfully compile it yourself.  Please feel free to contact me directly at aprovost@usgs.gov if you have any further questions about MODPATH other than reporting an issue with the code.
