### ISSUE TITLE
Multiple particle starting locations for multiple release times?

### ISSUE THREAD

**Issue by kmarkovich** [MODFLOW-USGS/modpath-v7#32]
I am trying to emulate plume evolution with particles getting added at multiple release times from a decaying source (number of particles getting added decrease over time). Is it possible to associate  a unique starting location input for each release time? Or is the starting location input constant with the multiple release times options.

**Comment by aprovost-usgs** [comment]
@kmarkovich-intera Assignment of release times is by particle group -- each particle group has its own time or sequence of times.  Assignment of particle starting locations is also by particle group, and all locations in a given particle group are on the same release schedule.  To associate a unique starting location with each release time, you would put each time/location pairing in a separate particle group.  Alternatively, if it wouldn't result in too many particles to be practical, you could put all the times and locations in a single particle group (so at each time, all locations will release a particle, most of which you don't care about) and extract only the relevant time/location pairings in postprocessing.  I hope this answers your question.

For help with using MODPATH 7 or questions regarding its existing capabilities, other users on [MODFLOW Google Group](https://groups.google.com/g/modflow) might be able to offer advice, or I can be contacted directly at aprovost@usgs.gov.  Issues are best reserved for suspected bugs (with a clear and concise description of and evidence for the bug) or feature requests (with a clear and concise description of the desired capability and its utility, and ideally, alternatives that have been considered).

**Comment by kmarkovich** [comment]
It does, thank you!

**Comment by aprovost-usgs** [comment]
Great!  Thanks for your interest in MODPATH.
